# Generated by Django 6.0.7 on 2026-07-31 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FACULTAD',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.facultad')),
            ],
            options={
                'db_table': 'CARRERA',
            },
        ),
    ]
