# Generated by Django 6.0.7 on 2026-07-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cod_sis_est', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres_est', models.CharField(max_length=100)),
                ('apellidos_est', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.carrera')),
            ],
            options={
                'db_table': 'ESTUDIANTE',
            },
        ),
    ]
