# Generated by Django 6.0.7 on 2026-07-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_doc', models.CharField(max_length=100)),
                ('apellidos_doc', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
             options={
                'db_table' : 'DOCENTE',
            }
        ),
    ]
