# Generated by Django 6.0.7 on 2026-07-31 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_docente_alter_estudiante_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.docente')),
            ],
            options={
                'db_table': 'MATERIA',
            },
        ),
    ]
