# Generated by Django 6.0.7 on 2026-07-31 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=10)),
                ('cupo', models.IntegerField(default=40)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.materia')),
            ],
            options={
                'db_table': 'GRUPO',
            },
        ),
    ]
