# Generated by Django 6.0.7 on 2026-07-31 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id_kardex', models.AutoField(primary_key=True, serialize=False)),
                ('gestion', models.IntegerField()),
                ('periodo', models.CharField(max_length=10)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.inscripcion')),
            ],
            options={
                'db_table': 'KARDEX',
            },
        ),
    ]
